#!/usr/bin/env python3
"""Verify project-index.json against the filesystem and regenerate DESIGN-REFERENCE.md.

Run:  python3 reference/verify.py          # verify + regenerate
      python3 reference/verify.py --check  # verify only, non-zero exit on drift
"""
import json, os, subprocess, sys, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
IDX  = os.path.join(HERE, "project-index.json")
MD   = os.path.join(HERE, "DESIGN-REFERENCE.md")
SITE_VIDEOS = os.path.normpath(os.path.join(HERE, "..", "public", "assets", "videos"))

def dur(p):
    try:
        r = subprocess.run(["ffprobe","-v","error","-show_entries","format=duration",
                            "-of","default=nw=1:nk=1",p], capture_output=True, text=True, timeout=30)
        return float(r.stdout.strip())
    except Exception:
        return None

def main():
    d = json.load(open(IDX))
    problems, checked = [], 0

    for r in d["routes"]:
        for p in r.get("local", []):
            checked += 1
            if not os.path.exists(p):
                problems.append(f'{r["route"]}: local missing -> {p}')
        med = r.get("media") or {}
        for v in (med.get("videos") or []):
            if not isinstance(v, dict):
                continue
            checked += 1
            p = v["path"]
            if not os.path.exists(p):
                problems.append(f'{r["route"]}: video missing -> {p}')
                continue
            actual = dur(p)
            if actual and abs(actual - v["seconds"]) > 0.5:
                problems.append(f'{r["route"]}: duration drift {os.path.basename(p)} '
                                f'index={v["seconds"]} actual={actual:.2f}')

    archived_offline = []
    for n in d.get("notOnSite", []):
        checked += 1
        if not os.path.exists(n["local"]):
            if n.get("archived"):
                archived_offline.append(n["name"])
            else:
                problems.append(f'notOnSite {n["name"]}: missing -> {n["local"]}')

    # site videos: confirm every onSite entry marked FULL matches its source duration
    for r in d["routes"]:
        for v in ((r.get("media") or {}).get("videos") or []):
            if isinstance(v, dict) and v.get("onSite") and "FULL" in str(v["onSite"]):
                name = v["onSite"].split()[0]
                sp = os.path.join(SITE_VIDEOS, name)
                checked += 1
                if not os.path.exists(sp):
                    problems.append(f'{r["route"]}: site video missing -> {name}')
                else:
                    sd = dur(sp)
                    if sd and abs(sd - v["seconds"]) > 1.0:
                        problems.append(f'{r["route"]}: {name} is NOT full length '
                                        f'(site={sd:.2f}s source={v["seconds"]}s) - re-encode from source')

    arc = d.get("archivedProjects", {})
    vol_mounted = os.path.isdir("/Volumes/UnityProjectsArchive")
    print(f"checked {checked} paths, {len(problems)} problem(s)")
    for p in problems:
        print("  !", p)
    if archived_offline:
        print(f"  (archive volume {'mounted' if vol_mounted else 'NOT mounted'}; "
              f"expected-offline: {', '.join(archived_offline)})")
    if arc and arc.get("mounted") != vol_mounted:
        arc["mounted"] = vol_mounted
        json.dump(d, open(IDX, "w"), ensure_ascii=False, indent=2)

    if "--check" not in sys.argv:
        write_md(d, problems)
        print(f"regenerated {os.path.relpath(MD, os.getcwd())}")
    return 1 if problems and "--check" in sys.argv else 0

def write_md(d, problems):
    F = d["figmaFiles"]
    def flink(fk, node=None):
        f = F[fk]
        base = f'https://www.figma.com/{"slides" if f["type"]=="slides" else "design"}/{f["key"]}'
        return f'{base}?node-id={node.replace(":","-")}' if node else base

    o = []
    o.append("# ArtCenter Design Reference\n")
    o.append(f'Generated by `reference/verify.py` · scope: {d["scope"]}\n')
    o.append("This file is generated. Edit `project-index.json`, then re-run `python3 reference/verify.py`.\n")

    o.append("\n## Figma files\n")
    o.append("| File | Key | Type | Pages |")
    o.append("|---|---|---|---:|")
    for k, f in F.items():
        o.append(f'| [{f["name"]}]({flink(k)}) | `{f["key"]}` | {f["type"]} | {len(f["pages"])} |')

    o.append("\n## Routes published on ReDInAStrike.com\n")
    for r in d["routes"]:
        o.append(f'\n### `{r["route"]}` — {r["pageTitle"]}\n')
        o.append(f'*{r["displayTitle"]} · {r["date"]} · nav:{r["nav"]}*\n')
        if r.get("aliases"):
            o.append(f'**Also called:** {", ".join(r["aliases"])}\n')
        if r.get("local"):
            o.append("**Local:**\n")
            for p in r["local"]:
                mark = "" if os.path.exists(p) else " ⚠️ MISSING"
                o.append(f'- `{p}`{mark}')
            o.append("")
        if r.get("unity"):
            u = r["unity"]
            o.append(f'**Unity:** productName `{u["productName"]}` · editor {u["editor"]}'
                     + (f' · scene `{u["scene"]}`' if u.get("scene") else "") + "\n")
        if r.get("figma"):
            o.append("**Figma:**\n")
            for g in r["figma"]:
                if g.get("page"):
                    o.append(f'- [{g["name"]}]({flink(g["file"], g["page"])}) — `{g["page"]}` in {F[g["file"]]["name"]}')
                    if g.get("textNodes"):
                        o.append(f'  - {g["textNodes"]} text nodes')
                    if g.get("content"):
                        o.append(f'  - {g["content"]}')
                    for nid, what in (g.get("keyNodes") or {}).items():
                        o.append(f'  - `{nid}` — {what}')
                elif g.get("pages_all"):
                    o.append(f'- {F[g["file"]]["name"]}: {g["pages_all"]}')
            o.append("")
        med = r.get("media") or {}
        vids = [v for v in (med.get("videos") or []) if isinstance(v, dict)]
        if vids:
            o.append("**Video sources:**\n")
            o.append("| Source | Length | On site |")
            o.append("|---|---:|---|")
            for v in vids:
                nm = os.path.basename(v["path"])
                on = v.get("onSite") or "—"
                o.append(f'| `{nm}` | {v["seconds"]:.1f}s | {on} |')
            o.append("")
        if isinstance(med.get("videos"), str):
            o.append(f'**Video:** {med["videos"]}\n')
        if med.get("unattributed"):
            o.append(f'**Unattributed in same folder:** {", ".join(med["unattributed"])}\n')
        if med.get("hypothesis"):
            o.append(f'> Hypothesis (unconfirmed): {med["hypothesis"]}\n')
        if r.get("docs"):
            o.append("**Docs:** " + ", ".join(f'`{x}`' for x in r["docs"]) + "\n")
        o.append(f'**On site now:** {r["siteStatus"]}\n')
        if r.get("gaps"):
            o.append("**Gaps:**\n")
            for g in r["gaps"]:
                o.append(f'- {g}')
            o.append("")

    o.append("\n## Projects with no route\n")
    for n in d["notOnSite"]:
        mark = "" if os.path.exists(n["local"]) else " ⚠️ MISSING"
        o.append(f'\n### {n["name"]}\n')
        o.append(f'- `{n["local"]}`{mark}')
        if n.get("unity"):
            o.append(f'- Unity: `{n["unity"]["productName"]}` · {n["unity"]["editor"]}')
        if n.get("art"):
            o.append(f'- Art: `{n["art"]}`')
        if n.get("figma"):
            g = n["figma"]
            o.append(f'- Figma: [{g["name"]}]({flink(g["file"], g["page"])})')
        o.append(f'- {n["note"]}')

    arc = d.get("archivedProjects")
    if arc:
        o.append("\n## Archived to external volume\n")
        o.append(f'**{arc["volume"]}** — archived {arc["date"]} — '
                 f'currently **{"mounted" if arc["mounted"] else "NOT mounted"}**\n')
        o.append(f'{arc["scheme"]}\n')
        o.append(f'> ⚠️ {arc["warning"]}\n')
        for e in arc["entries"]:
            o.append(f'- `{e}`')
        o.append("")

    o.append("\n## Gotchas\n")
    for g in d["gotchas"]:
        o.append(f'- {g}')

    o.append(f'\n## Last verification\n')
    o.append(f'`{datetime.date.today()}` — {len(problems)} problem(s)')
    for p in problems:
        o.append(f'- ⚠️ {p}')
    o.append("")
    open(MD, "w").write("\n".join(o))

sys.exit(main())
